In [158]:
from predictor import Predictor

In [3]:
from tensorflow.keras.models import load_model
models = []
scalers_1 = []
scalers_2 = []
for i in range(1, 3) :
    print(i)
    model_path = './ml_tools/model_'+str(i)+'.h5'
    model = load_model(model_path)
    models.append(model)

1
2


In [2]:
load_model('./ml_tools/model_2.h5')

NameError: name 'load_model' is not defined

In [4]:
df

NameError: name 'df' is not defined

In [159]:
predictor = Predictor()

/usr/local/lib/python3.9/site-packages/sklearn/base.py:288: UserWarning: Trying to unpickle estimator MinMaxScaler from version 1.2.2 when using version 1.2.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


TypeError: __init__() got an unexpected keyword argument 'fn'

In [135]:
model_path = '/Users/ghita/Desktop/fm/projects/AGRO-Dashboard/ml_tools/P075_24h_3h_CNNLSTM.h5'
scaler1_path = '/Users/ghita/Desktop/fm/projects/AGRO-Dashboard/ml_tools/scaler1.pkl'
scaler2_path = '/Users/ghita/Desktop/fm/projects/AGRO-Dashboard/ml_tools/scaler2.pkl'
       
# Charger le modèle pré-entraîné 
model = load_model(model_path)

# Charger le premier scaler depuis le fichier
with open(scaler1_path, 'rb') as file1:
    sc1 = joblib.load(file1)

# Charger le deuxième scaler depuis le fichier
with open(scaler2_path, 'rb') as file2:
    sc2 = joblib.load(file2)

/usr/local/lib/python3.9/site-packages/sklearn/base.py:288: UserWarning: Trying to unpickle estimator MinMaxScaler from version 1.2.2 when using version 1.2.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


In [153]:
X_test=np.array(X_test, dtype=np.float32)
X_test

array([[373.14343, 348.4571 ],
       [373.14343, 348.4571 ],
       [373.14343, 348.4571 ],
       ...,
       [373.21353, 369.46033],
       [373.117  , 369.36435],
       [373.0205 , 369.26837]], dtype=float32)

In [154]:
X_test_sc = sc1.transform(X_test)
X_test_sc

/usr/local/lib/python3.9/site-packages/sklearn/base.py:409: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


array([[0.79446435, 0.4354127 ],
       [0.79446435, 0.4354127 ],
       [0.79446435, 0.4354127 ],
       ...,
       [0.7949307 , 0.56869656],
       [0.7942884 , 0.56808764],
       [0.79364634, 0.5674785 ]], dtype=float32)

In [155]:
X_test_sc = X_test_sc[np.newaxis, :, :]
X_test_sc.shape

(1, 1440, 2)

In [156]:
y = model.predict(X_test_sc)
y

1/1 [==============================] - 1s 506ms/step


array([[[0.5655872 ],
        [0.5653288 ],
        [0.5652324 ],
        [0.5650815 ],
        [0.5649276 ],
        [0.5646952 ],
        [0.56457853],
        [0.56466496],
        [0.5647727 ],
        [0.56468177],
        [0.56457436],
        [0.56435263],
        [0.5640232 ],
        [0.56374574],
        [0.563459  ],
        [0.56328607],
        [0.56307584],
        [0.56302774],
        [0.5631863 ],
        [0.5633254 ],
        [0.56345534],
        [0.56345755],
        [0.5635291 ],
        [0.5634052 ],
        [0.56320816],
        [0.5631255 ],
        [0.56314886],
        [0.56319726],
        [0.5629978 ],
        [0.56284446],
        [0.56266075],
        [0.56251645],
        [0.5623086 ],
        [0.5619749 ],
        [0.561828  ],
        [0.56155086],
        [0.5613029 ],
        [0.56100094],
        [0.5606742 ],
        [0.5604481 ],
        [0.56032276],
        [0.56046474],
        [0.56053215],
        [0.5603119 ],
        [0.5600698 ],
        [0

In [157]:
y_pred_reshaped = y.reshape(-1, y.shape[-2])
y_pred = sc2.inverse_transform(y_pred_reshaped)
y_pred

array([[368.9703 , 368.9296 , 368.9144 , 368.89062, 368.8664 , 368.82977,
        368.8114 , 368.82498, 368.84198, 368.82767, 368.81073, 368.7758 ,
        368.72385, 368.68015, 368.63495, 368.60773, 368.5746 , 368.567  ,
        368.59198, 368.61392, 368.6344 , 368.63474, 368.646  , 368.62646,
        368.59543, 368.5824 , 368.5861 , 368.59372, 368.5623 , 368.53812,
        368.5092 , 368.48645, 368.45367, 368.4011 , 368.37793, 368.3343 ,
        368.2952 , 368.24762, 368.19614, 368.1605 , 368.14075, 368.16312,
        368.17374, 368.13904, 368.1009 , 368.1081 , 368.08505, 368.06094,
        368.04187, 368.0315 , 368.0472 , 368.04843, 368.06393, 368.07816,
        368.07465, 368.08218, 368.09155, 368.08176, 368.0607 , 368.04135,
        368.03793, 368.03687, 368.03174, 367.98288, 367.93472, 367.8692 ,
        367.85342, 367.84985, 367.8465 , 367.86417, 367.87085, 367.88226,
        367.90152, 367.91006, 367.92834, 367.91772, 367.89944, 367.88904,
        367.88342, 367.87674, 367.8387

In [51]:
# Create a DatetimeIndex with a start time of '2023-06-12 16:10:00' and a frequency of one minute
date_rng = pd.date_range(start=preprocessor.last_recorded_date, periods=180, freq='1min')

# Create a DataFrame with the array and the DatetimeIndex
df_pred = pd.DataFrame(y_pred.T, index=date_rng)

# Rename the columns to 'date' and 'prediction'
df_pred = df_pred.reset_index()
df_pred.columns = ['date', 'prediction']

# Add one minute to each row in the 'date' column
#df_pred['date'] = df_pred['date'].apply(lambda x: x + pd.Timedelta(minutes=1))
df_pred


date  prediction
0   2023-06-12 16:10:00  346.696228
1   2023-06-12 16:11:00  346.675781
2   2023-06-12 16:12:00  346.662537
3   2023-06-12 16:13:00  346.648285
4   2023-06-12 16:14:00  346.627350
..                  ...         ...
175 2023-06-12 19:05:00  346.207611
176 2023-06-12 19:06:00  346.231384
177 2023-06-12 19:07:00  346.245148
178 2023-06-12 19:08:00  346.247345
179 2023-06-12 19:09:00  346.238800

[180 rows x 2 columns]

In [67]:
def predict_3h(df, date, features):
    #date = df[['Date']].max()
    X_test = df[features][:1440]
    X_test_sc = sc1.transform(X_test)
    X_test_sc = X_test_sc[np.newaxis, :, :]
    y = model.predict(X_test_sc)
    y_pred_reshaped = y.reshape(-1, y.shape[-2])
    y_pred = sc2.inverse_transform(y_pred_reshaped)

    date_rng = pd.date_range(start=date, periods=180, freq='1min')
    # Create a DataFrame with the array and the DatetimeIndex
    df_pred = pd.DataFrame(y_pred.T, index=date_rng)

    # Rename the columns to 'date' and 'prediction'
    df_pred = df_pred.reset_index()
    df_pred.columns = ['date', 'prediction']

    return df_pred


In [72]:
predict_3h(preprocessor.filtred_24h, preprocessor.last_recorded_date, features = ['MV1', 'CV1'])

1/1 [==============================] - 0s 326ms/step


date  prediction
0   2023-06-12 16:10:00  346.696228
1   2023-06-12 16:11:00  346.675781
2   2023-06-12 16:12:00  346.662537
3   2023-06-12 16:13:00  346.648285
4   2023-06-12 16:14:00  346.627350
..                  ...         ...
175 2023-06-12 19:05:00  346.207611
176 2023-06-12 19:06:00  346.231384
177 2023-06-12 19:07:00  346.245148
178 2023-06-12 19:08:00  346.247345
179 2023-06-12 19:09:00  346.238800

[180 rows x 2 columns]

In [14]:
import requests
import json
import pandas as pd

url = "https://eu-west-2.aws.data.mongodb-api.com/app/data-rpqya/endpoint/data/v1/action/find"

documents_list = []
for collection in ['P075', 'P092'] :
    # Specify the fields to project in the "projection" field of the payload
    payload = json.dumps({
        "dataSource": "Cluster0",
        "database": "agrodaraa",
        "collection": collection,
        "sort": {"Date": -1},
        "limit": 1440,
        "projection": {"CV1": 1, "MV1": 1, "Date": 1}
    })
    headers = {
        "apiKey": "nzyQOL6Q8MzrC7ReUgDVmiqVYcXh1o7SUdI4sEiVbjSx4TUrXz7tJVJlpV5lgPiV",
        "Content-Type": "application/ejson",
        "Accept": "application/json",
    }

        # Make the POST request
    response = requests.request("POST", url, headers=headers, data=payload)

    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()
    else:
        print(f"Request failed with status code {response.status_code}")
    documents_list.append(data['documents'])

# Create a DataFrame from the list of dictionaries
x = pd.DataFrame(documents_list[0])

In [16]:
x.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1440 non-null   object 
 1   MV1     1440 non-null   float64
 2   CV1     1440 non-null   float64
 3   _id     1440 non-null   object 
dtypes: float64(2), object(2)
memory usage: 45.1+ KB


In [17]:
df = x.copy()
df['Date'] = pd.to_datetime(df['Date'], format="%Y-%m-%dT%H:%M:%SZ")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   Date    1440 non-null   datetime64[ns]
 1   MV1     1440 non-null   float64       
 2   CV1     1440 non-null   float64       
 3   _id     1440 non-null   object        
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 45.1+ KB


In [30]:
date = x[['Date']].max()
pd.date_range(start=date['Date'], periods=180, freq='1min')

DatetimeIndex(['2023-06-12 15:10:00+00:00', '2023-06-12 15:11:00+00:00',
               '2023-06-12 15:12:00+00:00', '2023-06-12 15:13:00+00:00',
               '2023-06-12 15:14:00+00:00', '2023-06-12 15:15:00+00:00',
               '2023-06-12 15:16:00+00:00', '2023-06-12 15:17:00+00:00',
               '2023-06-12 15:18:00+00:00', '2023-06-12 15:19:00+00:00',
               ...
               '2023-06-12 18:00:00+00:00', '2023-06-12 18:01:00+00:00',
               '2023-06-12 18:02:00+00:00', '2023-06-12 18:03:00+00:00',
               '2023-06-12 18:04:00+00:00', '2023-06-12 18:05:00+00:00',
               '2023-06-12 18:06:00+00:00', '2023-06-12 18:07:00+00:00',
               '2023-06-12 18:08:00+00:00', '2023-06-12 18:09:00+00:00'],
              dtype='datetime64[ns, UTC]', length=180, freq='T')

In [1]:
from predictor import Predictor

# Define object Predictor
predictor = Predictor()

# Fetch data ('Date', 'CV1', 'MV1') of all availble dfs in mongo API
dfs = predictor.fetch()
predictions = predictor.predict_3h(cv = 2)
dfs[1].info()

/usr/local/lib/python3.9/site-packages/sklearn/base.py:288: UserWarning: Trying to unpickle estimator MinMaxScaler from version 1.2.2 when using version 1.2.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(


1/1 [==============================] - 2s 2s/step
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1440 non-null   object 
 1   _id     1440 non-null   object 
 2   MV1     1440 non-null   float64
 3   CV1     1440 non-null   float64
dtypes: float64(2), object(2)
memory usage: 45.1+ KB


In [2]:
predictor.predictions

[                         Date  prediction
 0   2023-06-12 15:10:00+00:00  368.970367
 1   2023-06-12 15:11:00+00:00  368.929596
 2   2023-06-12 15:12:00+00:00  368.914398
 3   2023-06-12 15:13:00+00:00  368.890625
 4   2023-06-12 15:14:00+00:00  368.866394
 ..                        ...         ...
 175 2023-06-12 18:05:00+00:00  366.661591
 176 2023-06-12 18:06:00+00:00  366.670715
 177 2023-06-12 18:07:00+00:00  366.673370
 178 2023-06-12 18:08:00+00:00  366.656311
 179 2023-06-12 18:09:00+00:00  366.643372
 
 [180 rows x 2 columns],
                          Date  prediction
 0   2023-06-12 10:24:00+00:00  369.719055
 1   2023-06-12 10:25:00+00:00  369.468781
 2   2023-06-12 10:26:00+00:00  369.246948
 3   2023-06-12 10:27:00+00:00  369.086823
 4   2023-06-12 10:28:00+00:00  368.961182
 ..                        ...         ...
 175 2023-06-12 13:19:00+00:00  366.609619
 176 2023-06-12 13:20:00+00:00  366.665375
 177 2023-06-12 13:21:00+00:00  366.674622
 178 2023-06-12 13:22:00+00

In [7]:
predictions[0]['prediction']

0      368.970367
1      368.929596
2      368.914398
3      368.890625
4      368.866394
          ...    
175    366.661591
176    366.670715
177    366.673370
178    366.656311
179    366.643372
Name: prediction, Length: 180, dtype: float32

In [60]:
dfs[1].fillna(method='ffill', inplace=True)
dfs[0].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1440 entries, 0 to 1439
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    1440 non-null   object 
 1   MV1     1440 non-null   float64
 2   CV1     1440 non-null   float64
 3   _id     1440 non-null   object 
dtypes: float64(2), object(2)
memory usage: 45.1+ KB
